# Generated by Django 4.2.11 on 2024-07-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
