# Generated by Django 5.0.3 on 2024-03-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhod',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminhod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adminhod',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='password',
        ),
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='password',
        ),
    ]
